name: Standard Ruby

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@v1
        with:
          ruby-version: '3.1.2'